/* ============================================================
   SITEM Academy — ข้อมูลบทเรียนทั้งหมด (แก้เนื้อหา "ที่ไฟล์นี้")
   แต่ละบท: id, icon, color, eyebrow(หมวด), name, tagline, description,
            howto[], videoId, docs[], demo(ถ้ามี), quizLink
   * ไฟล์นี้ต้องอยู่โฟลเดอร์เดียวกับ index.html เสมอ *
   ============================================================ */
const PRODUCTS = [
  { id:"company", icon:"building", color:"var(--blue-500)", eyebrow:"ONBOARDING",
    name:"รู้จัก SITEM", tagline:"ประวัติบริษัท วิสัยทัศน์ และมาตรฐาน ISO 9001:2015",
    description:"Site Preparation Management (SITEM) คือผู้เชี่ยวชาญด้านการออกแบบ ก่อสร้าง และดูแลรักษา Data Center รวมถึงจัดจำหน่ายอุปกรณ์ระดับโลก ด้วยมาตรฐาน ISO 9001:2015 — Data Center ต้องถูกสร้างโดยมืออาชีพ",
    howto:["ทำความเข้าใจวิสัยทัศน์และบริการหลักของ SITEM","รู้จักกลุ่มผลิตภัณฑ์ของบริษัท","ศึกษามาตรฐานคุณภาพและความปลอดภัยในงาน Data Center"],
    videoId:"https://drive.google.com/file/d/13YWs7W5cTuxur90HHpvsDUpA9kZpYYZs/view?usp=sharing",
    docs:[
      {title:"ไฟล์วิดีโอ รู้จัก SITEM", url:"https://drive.google.com/file/d/13YWs7W5cTuxur90HHpvsDUpA9kZpYYZs/view?usp=sharing"},
    ],
    quizLink:null,
  },
  { id:"generator", icon:"zap", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Generator", tagline:"เครื่องกำเนิดไฟฟ้าสำรอง",
    description:"เครื่องกำเนิดไฟฟ้าสำรองสำหรับ Data Center จ่ายไฟเมื่อไฟหลักดับเป็นเวลานาน เพื่อให้ระบบทำงานต่อเนื่องไม่สะดุด",
    howto:["ตรวจระดับน้ำมันเชื้อเพลิงและแบตเตอรี่สตาร์ท","ทดสอบเดินเครื่อง (Test Run) ตามรอบ","ตรวจระบบระบายความร้อนและไอเสีย"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Diesel Generator", url:"https://drive.google.com/file/d/1RjpPSaMVWbkX6vnpQefVF2g7kdHpenYT/view?usp=sharing"},
    ],
    tools:[{title:"เครื่องคำนวณน้ำมันเชื้อเพลิง Genset (Fuel Calculator)", url:"genset-fuel-calculator.html"}],
    quizLink:"#",
  },
  { id:"activefilter", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Active Filter", tagline:"Active Harmonic Filter (AHF) — ปรับปรุงคุณภาพไฟฟ้า / ลดฮาร์มอนิก",
    description:"Active Harmonic Filter (AHF) คืออุปกรณ์ปรับปรุงคุณภาพไฟฟ้าแบบไดนามิก ทำงานโดยวัดกระแสโหลดแบบเรียลไทม์และฉีดกระแสชดเชยที่ตรงข้ามกับฮาร์มอนิก เพื่อหักล้างความเพี้ยน (THD) ในระบบ ต่างจากฟิลเตอร์แบบ Passive ที่ทำงานที่ความถี่คงที่ AHF ปรับตัวตามโหลดที่เปลี่ยนแปลงได้ตลอดเวลา ผลที่ได้คือลด THD จากระดับ ~16% ลงเหลือต่ำกว่า 3% ทำให้อุปกรณ์ Data Center ทำงานเสถียร ลดความร้อน และประหยัดพลังงาน",
    howto:[
      "วัดค่า THD (Total Harmonic Distortion) ของระบบก่อนติดตั้ง เพื่อเลือกขนาด AHF ที่เหมาะสม",
      "ติดตั้ง AHF แบบขนาน (Parallel) กับโหลดหลัก ไม่ต้องตัดไฟระบบ",
      "ตั้งค่าโมดูล DSP ให้ตรวจจับฮาร์มอนิกและฉีดกระแสชดเชยอัตโนมัติ",
      "ตรวจสอบค่า THD และ Power Factor หลังติดตั้งให้อยู่ในเกณฑ์มาตรฐาน (THD < 5%)",
      "ตรวจบำรุงรักษาและทำความสะอาดฟิลเตอร์ตามรอบที่กำหนด",
    ],
    videoId:"https://drive.google.com/file/d/1RcCCen2DbwYFk_8n5aCNkoogafcYbHbt/view?usp=sharing",
    docs:[
      {title:"เอกสาร AHF (1)", url:"https://drive.google.com/file/d/15Hd58osl8OY9J1JilC5yR4FhJ8t3yIYK/view?usp=sharing"},
      {title:"เอกสาร AHF (2)", url:"https://drive.google.com/file/d/1UVhgAYe_tRaGLY2LeHH1DhHpU2FAzQIn/view?usp=sharing"},
      {title:"เอกสาร AHF (3)", url:"https://drive.google.com/file/d/1pAeoHoNdO9beQa_gcLO_TkTWHKpndqF2/view?usp=sharing"},
      {title:"วิดีโอเพิ่มเติม (Folder)", url:"https://drive.google.com/drive/folders/19-fs3VheU34nVhtKSgnw_59SaxERxzkY?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"ats", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"ATS", tagline:"Automatic Transfer Switch",
    description:"สวิตช์สับเปลี่ยนแหล่งจ่ายไฟอัตโนมัติ จากไฟหลักไปยังเครื่องกำเนิดไฟฟ้าเมื่อไฟดับ และสลับกลับเมื่อไฟหลักมาปกติ",
    howto:["เข้าใจลำดับการสลับแหล่งไฟ (Utility/Generator)","ตั้งค่าเวลาหน่วงและเงื่อนไขการสลับ","ทดสอบการสลับอัตโนมัติตามรอบ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"เอกสาร Training — ATS Asco", url:"https://drive.google.com/file/d/1342RAq5KhJd3EIpaLT9VP90EbzQ_82YF/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"sts", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"STS", tagline:"Static Transfer Switch",
    description:"สวิตช์สับเปลี่ยนแหล่งจ่ายไฟแบบสถานะคงที่ ความเร็วสูง สลับแหล่งไฟได้ในเสี้ยววินาทีโดยโหลดไม่สะดุด",
    howto:["เข้าใจหลักการสลับแบบไร้รอยต่อ (Seamless)","ตรวจสอบแหล่งไฟทั้งสองฝั่งให้พร้อม","ทดสอบการสลับและตรวจสัญญาณเตือน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"loadbank", icon:"gauge", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Loadbank", tagline:"อุปกรณ์ทดสอบโหลด",
    description:"อุปกรณ์จำลองโหลดไฟฟ้า เพื่อทดสอบเครื่องกำเนิดไฟฟ้าและ UPS ว่ารับโหลดเต็มพิกัดได้จริงและเสถียร",
    howto:["กำหนดระดับโหลดที่ต้องการทดสอบ","ค่อยๆ เพิ่มโหลดเป็นขั้นและบันทึกค่า","ตรวจอุณหภูมิและแรงดันระหว่างทดสอบ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Loadbank Installation & Operation Manual", url:"https://drive.google.com/file/d/1wV71znOD4dR8bgUZB7uKC01meXOTM-cd/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"pdu", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"PDU / รางไฟฟ้า", tagline:"Power Distribution Unit / Busway",
    description:"ระบบจ่ายและกระจายไฟฟ้าไปยังตู้แร็ค พร้อมรางไฟฟ้า (Busway) ที่ยืดหยุ่น ติดตั้งง่าย และวัดค่าการใช้พลังงานรายจุดได้",
    howto:["วางผังการจ่ายไฟให้สมดุลแต่ละเฟส","ติดตั้ง PDU/Busway และต่อโหลดตามพิกัด","มอนิเตอร์การใช้พลังงานรายแร็ค"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Monitored & Switch PDU", url:"https://drive.google.com/file/d/1VmHe3ql2y8Gqixuf7Bm8Ow66CsZBRcxP/view?usp=sharing"},
      {title:"Basic PDU", url:"https://drive.google.com/file/d/11nNdV3FrioKZwJHlNPNPtz-HgyIR5gUI/view?usp=sharing"},
      {title:"LIMAZ Switched PDU", url:"https://drive.google.com/file/d/1epkVNm_sCZ74pOJEmtPaGdIPuxOtwUZ9/view?usp=sharing"},
      {title:"rPDU Product Description", url:"https://drive.google.com/file/d/1pr5U2gLv6i7wvF45rXYzvKy9oLs6Sme5/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"ups-huawei", icon:"battery", color:"var(--amber-500)", eyebrow:"UPS",
    name:"UPS — Huawei", tagline:"Modular UPS ซีรีส์ UPS5000 — High Efficiency & AI Predictive",
    description:"Huawei UPS5000 Series คือ Modular UPS ระดับ Enterprise สำหรับ Data Center ขนาดกลาง-ใหญ่ ออกแบบให้ขยายกำลังได้แบบ Hot-swap โดยไม่ต้องหยุดระบบ รุ่นหลัก ได้แก่ UPS5000-E (30–800 kVA, ประสิทธิภาพสูงสุด 96%), UPS5000-H (400–1600 kVA, โมดูล 100 kVA/3U, S-ECO Mode ประสิทธิภาพสูงถึง 99.1%) และ UPS5000-A (Tower สำหรับ Data Center ระดับ Primary) ระบบ iPower ใช้ AI วิเคราะห์สุขภาพชิ้นส่วนล่วงหน้า (Predictive Maintenance) และรองรับแรงดัน Input กว้างถึง 138–483 V AC",
    howto:[
      "เลือกรุ่นให้เหมาะกับขนาด: UPS5000-E สำหรับ 30–800 kVA, UPS5000-H สำหรับงานขนาดใหญ่ ≥ 400 kVA",
      "วางแผนจำนวนโมดูลและ Redundancy (N+1 หรือ 2N) ตาม TIER ที่ต้องการ",
      "ติดตั้ง Power Module แบบ Hot-swap ในแร็ค ไม่ต้องหยุดระบบเมื่อขยายกำลัง",
      "เชื่อมต่อ iPower Management System เพื่อ Monitor และ Predictive Maintenance",
      "ตั้งค่า S-ECO Mode เพื่อประสิทธิภาพสูงสุด และตรวจสอบ THD Output ให้ < 2%",
    ],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"เอกสาร Huawei UPS5000 Series", url:"https://drive.google.com/file/d/1lpuooFkykmclfe_B_ZWhOuzUChQOt8Os/view?usp=drive_link"},
      {title:"Huawei Support Portal (Data Center Facility)", url:"https://support.huawei.com/enterprise/en/category/data-center-facility-pid-1657247194270?submodel=doc"},
    ],
    openQ:[
      {q:"UPS แบบ Offline (Standby), Line-Interactive และ Online Double-Conversion แตกต่างกันอย่างไร? แต่ละแบบเหมาะกับงานประเภทใด และทำไม Data Center จึงต้องใช้แบบ Online Double-Conversion?", url:"https://www.fs.com/blog/comparison-of-ups-topologies-line-interactive-vs-online-vs-offline-3538.html"},
    ],
    quizLink:"#",
  },
  { id:"ups-sentryum", icon:"battery", color:"var(--amber-500)", eyebrow:"UPS",
    name:"UPS — Riello Sentryum", tagline:"Static UPS 10–120 kVA Transformerless สำหรับ Data Center เล็ก-กลาง",
    description:"Riello Sentryum คือ UPS 3 Phase Online Double-Conversion รุ่นใหม่ปี 2023 ใช้ Dual-core DSP + Three-level Inverter ประสิทธิภาพสูงสุด 96.6% (pf 1.0) ทนอุณหภูมิได้ถึง 40°C THDv < 1.5% กับโหลด Non-linear มีตัวเลือกตู้ 3 แบบ (Compact / Active / Xtend) รองรับ Overload 125% นาน 10 นาที ขนานได้สูงสุด 8 ตัว เหมาะกับ Server Room และ Data Center ขนาดเล็ก-กลาง",
    howto:[
      "คำนวณโหลดรวม (kVA) และ Power Factor เพื่อเลือกขนาด Sentryum ที่มี Headroom ≥ 20%",
      "เลือกแบบตู้ให้เหมาะกับพื้นที่: Compact (พื้นที่แคบ), Active (มาตรฐาน), Xtend (Battery เพิ่ม)",
      "ติดตั้ง เชื่อม Static Bypass และต่อสายกราวด์ให้ถูกต้อง",
      "ตั้งค่า SNMP Card และ EPO เชื่อมกับระบบ Monitoring",
      "PM ทุก 6 เดือน: ตรวจ/วัดแรงดันแบตเตอรี่รายเซลล์, ทดสอบ Transfer to Bypass",
    ],
    videoId:"https://drive.google.com/file/d/1yH7zstkQrmFHIHVgob6WqR_Sa70vfP5s/view?usp=sharing",
    docs:[
      {title:"สไลด์ Riello Sentryum", url:"https://drive.google.com/file/d/14U7X0QKZBtSRtsY0ZLRhb9sMjisfNDG7/view?usp=sharing"},
    ],
    openQ:[
      {q:"การเปลี่ยนบอร์ด Control ของ Riello Sentryum มีขั้นตอนอย่างไร? ต้องเตรียมอะไรบ้างก่อนเปลี่ยน และควรระวังอะไรขณะทำงาน?"},
    ],
    quizLink:"#",
  },
  { id:"ups-mp2", icon:"battery", color:"var(--amber-500)", eyebrow:"UPS",
    name:"UPS — Riello MP2", tagline:"Modular UPS 120–6400 kW Silicon Carbide สำหรับ Data Center ขนาดใหญ่",
    description:"Riello Multi Power2 (MP2) คือ Modular UPS ประสิทธิภาพสูงสุดในตลาด ใช้ชิป Silicon Carbide (SiC) ทำให้ได้ประสิทธิภาพ 98.1% ในโหมด Online Double-Conversion โมดูล Power 67 kW/3U Hot-swap ไม่ต้องหยุดระบบเมื่อเพิ่มกำลังหรือ Maintenance รองรับ 120–600 kW ต่อตู้ และขยายถึง 6400 kW ด้วยการขนาน 4 ระบบ เหมาะกับ Data Center ขนาดกลาง-ใหญ่ที่ต้องการ TIER สูงและ TCO ต่ำ",
    howto:[
      "วางแผน Capacity: เลือกจำนวนโมดูล 67 kW ที่ต้องการ และ Redundancy (N+1 หรือ 2N)",
      "ติดตั้งตู้ MP2 และใส่ Power Module แบบ Hot-swap ได้โดยไม่ต้องหยุดระบบ",
      "เชื่อมต่อ Battery Cabinet และตั้งค่าเวลาสำรองที่ต้องการ",
      "ตั้งค่า SNMP/EPO เชื่อมระบบ Monitoring และตั้ง Alarm Threshold",
      "PM: สามารถถอดเปลี่ยน Power Module หรือแบตเตอรี่ขณะระบบทำงานได้ (Hot-swap)",
    ],
    videoId:"https://drive.google.com/file/d/1Jgsw-3kRgfueVr5ReO5U6OuZ5o758yhq/view?usp=sharing",
    docs:[
      {title:"Manual MP2 (1)", url:"https://drive.google.com/file/d/1L63wWjzEtIDPDzZOF2pVQNmMgXBKmtnL/view?usp=sharing"},
      {title:"Manual MP2 (2)", url:"https://drive.google.com/file/d/1L1v3KIA4vvmddj5NnCXWMoH-_eyGdy80/view?usp=sharing"},
    ],
    openQ:[
      {q:"การอัปเดต Firmware ของ Riello MP2 ทำยังไง? ต้องเตรียมอะไรบ้าง มีความเสี่ยงอะไรที่ต้องระวัง และถ้า Firmware อัปเดตค้างกลางคันต้องทำอย่างไร?"},
    ],
    quizLink:"#",
  },
  { id:"battery", icon:"battery", color:"var(--amber-500)", eyebrow:"UPS",
    name:"Battery", tagline:"แบตเตอรี่สำรอง",
    description:"แบตเตอรี่สำรองสำหรับระบบ UPS ทั้งแบบตะกั่วกรด (VRLA) และลิเธียม เลือกให้เหมาะกับเวลาสำรองไฟและพื้นที่",
    howto:["เลือกชนิดและความจุแบตให้ตรงความต้องการ","ติดตั้งในที่ระบายอากาศและอุณหภูมิเหมาะสม","ตรวจสภาพและเปลี่ยนตามอายุการใช้งาน"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"UPS Lithium Battery — Components & Troubleshooting", url:"https://drive.google.com/file/d/1AgArN8t3jQpURR7frvYHQ-uiEyzko1Kx/view?usp=sharing"},
    ],
    tools:[{title:"เครื่องคำนวณแบตเตอรี่ UPS (Battery Calculator)", url:"ups-battery-calculator-v22.html"}],
    quizLink:"#",
  },
  { id:"dynamicups", icon:"battery", color:"var(--amber-500)", eyebrow:"UPS",
    name:"UPS — Active Power", tagline:"Flywheel UPS (CleanSource) — ไฟสำรองไร้แบตเตอรี่",
    description:"Active Power CleanSource คือ Flywheel UPS ที่สะสมพลังงานด้วยล้อหมุนความเร็วสูง (Kinetic Energy) แทนแบตเตอรี่ ให้ไฟสำรอง 15–30 วินาที เพียงพอสำหรับเครื่องกำเนิดไฟฟ้าสตาร์ท ด้วย Parallel Online Architecture จะแยก Input/Output อย่างสมบูรณ์และตัดฮาร์มอนิกออกจากโหลด ได้รับการรับรอง IEC 62040-3 Class 1 ข้อดีสำคัญ: TCO ต่ำกว่า UPS+Battery แบบเดิม 40%, โอกาสเสียน้อยกว่า 12 เท่า และปล่อย Carbon น้อยกว่า 9 เท่า",
    howto:[
      "เข้าใจหลักการ Flywheel: มอเตอร์เร่งล้อจนถึงความเร็วพิกัด แล้วคงความเร็วด้วย Magnetic Bearing",
      "เมื่อไฟหลักดับ ล้อหมุนถ่ายพลังงานกลับเป็นไฟฟ้าทันทีภายใน Millisecond",
      "ตรวจสอบความเร็วรอบและอุณหภูมิ Flywheel ผ่านหน้าจอ HMI",
      "ประสานงานกับ Generator: ระยะสำรองของ Flywheel ต้องนานกว่าเวลา Gen สตาร์ท (~10–20 วินาที)",
      "ตรวจ PM ตามรอบ: Magnetic Bearing, หัวต่อสายไฟฟ้า, และระบบระบายความร้อน",
    ],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"vycon", icon:"battery", color:"var(--amber-500)", eyebrow:"UPS",
    name:"UPS — Vycon", tagline:"Flywheel Energy Storage (VDC) — แทนแบตเตอรี่ใน UPS",
    description:"Vycon VDC Flywheel คือระบบกักเก็บพลังงานจลน์ (Kinetic Energy Storage) ที่ต่อเข้า DC Bus ของ UPS 3 เฟสโดยตรง เมื่อไฟหลักดับ Flywheel ปล่อยพลังงานรองรับโหลดทันที 20–40 วินาที ขณะ Generator สตาร์ท ใช้ Active Magnetic Bearing ลอยตัวโรเตอร์ไม่มีการสัมผัส ทำให้อายุการใช้งานยาวนานถึง 20 ปี เชื่อถือได้สูงกว่าแบตเตอรี่ VRLA ถึง 20 เท่า และประหยัดพื้นที่ 50–75% เทียบกับแบงค์แบตเตอรี่ขนาดเดียวกัน",
    howto:[
      "เชื่อมต่อ VDC Flywheel เข้า DC Bus ของ UPS ที่มีอยู่ (ไม่ต้องเปลี่ยน UPS เดิม)",
      "ระบบจะชาร์จ Flywheel ให้ถึงความเร็วพิกัดอัตโนมัติหลังติดตั้ง",
      "ตรวจสอบสถานะผ่าน HMI: ความเร็วรอบ, อุณหภูมิ, สถานะ Magnetic Bearing",
      "เมื่อไฟดับ VDC ปล่อยพลังงานค้ำโหลด 20–40 วินาทีโดยอัตโนมัติ ก่อน Generator Online",
      "ตรวจ PM: ไม่มีแบตเตอรี่ให้เปลี่ยน — ตรวจแค่สายไฟฟ้า, ระบายความร้อน และ Software ตามรอบปี",
    ],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Slide Vycon VDC Flywheel", url:"https://drive.google.com/file/d/1UaPNvo-plY2f4m6SjL4BIt2bE-C49fVv/view?usp=sharing"},
      {title:"โฟลเดอร์เอกสาร Vycon (รวมทุกไฟล์)", url:"https://drive.google.com/drive/folders/13pBb_hAT9HvrwmmM0rbTW5ixDJksVYNj?usp=drive_link"},
    ],
    quizLink:"#",
  },
  { id:"netman208", icon:"chart", color:"var(--amber-500)", eyebrow:"UPS",
    name:"Netman 208", tagline:"การ์ดจัดการเครือข่ายของ UPS (SNMP/Web)",
    description:"Netman 208 เป็นการ์ดสำหรับเชื่อมต่อและมอนิเตอร์ UPS ผ่านเครือข่าย (SNMP/HTTP) รองรับการอัปเดตเฟิร์มแวร์ (FW) และดึง Log เพื่อดูสถานะและเหตุการณ์ของ UPS",
    howto:["ติดตั้งการ์ด Netman 208 เข้ากับช่องของ UPS","ตั้งค่าเครือข่าย (IP) และเข้าหน้าเว็บจัดการ","อัปเดตเฟิร์มแวร์ (FW) และดึง Log เพื่อตรวจสอบ"],
    videoId:"https://www.youtube.com/watch?v=kQkwU7K1bf4",
    docs:[
      {title:"สรุปการ Update FW และ Load Log", url:"https://drive.google.com/file/d/1mMDYIEpLp8M8uuudjASPXsSw2TK9Twfv/view?usp=sharing"},
      {title:"คู่มือการใช้งาน (Manual)", url:"https://drive.google.com/file/d/1ZyVvJyZkznG6NL8BwYgXicR09V7cr94w/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"batterymonitoring", icon:"gauge", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Battery Monitoring", tagline:"ระบบเฝ้าระวังแบตเตอรี่",
    description:"ระบบเฝ้าระวังสุขภาพแบตเตอรี่รายเซลล์ (แรงดัน อุณหภูมิ ความต้านทานภายใน) แจ้งเตือนล่วงหน้าก่อนแบตเสื่อมจนใช้งานไม่ได้",
    howto:["ติดตั้งเซนเซอร์วัดรายเซลล์","ตั้งค่าเกณฑ์แจ้งเตือน","ดูแนวโน้มสุขภาพแบตเพื่อวางแผนเปลี่ยน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"genstart", icon:"zap", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Gen Start", tagline:"ระบบสั่งสตาร์ทเครื่องกำเนิดไฟฟ้า",
    description:"ระบบสั่งสตาร์ทเครื่องกำเนิดไฟฟ้าอัตโนมัติเมื่อตรวจพบไฟหลักดับ ให้แหล่งไฟสำรองพร้อมจ่ายในเวลาอันรวดเร็ว",
    howto:["เข้าใจสัญญาณสั่งสตาร์ทจากระบบไฟหลัก","ตั้งค่าเวลาหน่วงและเงื่อนไขสตาร์ท","ทดสอบการสตาร์ทอัตโนมัติตามรอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  /* demo: c7000-sim.html = เครื่องจำลอง STULZ C7000 */
  { id:"pac", icon:"snow", color:"var(--blue-400)", eyebrow:"COOLING",
    name:"Precision Air Conditioning", tagline:"ปรับอากาศความแม่นยำสูง (STULZ)",
    description:"ระบบปรับอากาศความแม่นยำสูงสำหรับ Data Center ควบคุมอุณหภูมิและความชื้นให้คงที่ตลอด 24 ชั่วโมง เพื่อให้อุปกรณ์ทำงานในสภาวะที่เหมาะสม",
    howto:["เข้าใจหลักการ Precision Cooling","ติดตั้ง CRAC/CRAH และจัดทิศทางลมเย็น/ลมร้อน","ควบคุมอุณหภูมิ ความชื้น และตรวจฟิลเตอร์"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"STULZ CyberAir CW E2 Customer Training", url:"https://drive.google.com/file/d/1RtKRKWC_Pz0He-yk_BwOM7mMrODhFu6W/view?usp=sharing"},
      {title:"Training — PAHU Presentation", url:"https://drive.google.com/file/d/1I0GChzbo2l_E8Xeiy3nGPreI3kMWAeDU/view?usp=sharing"},
    ],
    demo:"c7000-sim.html", quizLink:"#",
  },
  { id:"vrf", icon:"fan", color:"var(--blue-400)", eyebrow:"COOLING",
    name:"VRF / VRV", tagline:"ระบบปรับอากาศปริมาณน้ำยาแปรผัน",
    description:"ระบบปรับอากาศแบบปรับปริมาณน้ำยาแปรผัน (VRF/VRV) ประหยัดพลังงาน ยืดหยุ่นต่อการแบ่งโซน เหมาะกับพื้นที่สำนักงานและห้องสนับสนุน",
    howto:["ออกแบบการแบ่งโซนและคอยล์ภายใน","ติดตั้งชุดคอนเดนเซอร์และเดินท่อน้ำยา","ตั้งค่าควบคุมและตรวจประสิทธิภาพ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"VRF vs Chiller", url:"https://drive.google.com/file/d/1gRRBwj_pEVSQxsV4ZDvcO0tAjLGf0V1p/view?usp=sharing"},
      {title:"Midea VRF Solution", url:"https://drive.google.com/file/d/18QzEn35fiCP_YsbyjgdS_VlysI7xFMRL/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"monitoring", icon:"chart", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"Power & Environmental Monitoring", tagline:"Packet Power / EMX",
    description:"ระบบมอนิเตอร์พลังงานและสภาพแวดล้อมแบบเรียลไทม์ด้วย Packet Power และ EMX เฝ้าระวังการใช้พลังงาน อุณหภูมิ และความชื้นภายใน Data Center",
    howto:["ติดตั้ง Smart Power Cables วัดพลังงานรายจุด","เชื่อม Gateway เข้าระบบเครือข่าย","ตั้งค่า Alerts & Policies แจ้งเตือนค่าผิดปกติ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Training — King Pigeon", url:"https://drive.google.com/file/d/1Hr6uDkplODL-ymqaDlTcEw5oFHXMcFHC/view?usp=sharing"},
      {title:"MST Customer Training", url:"https://drive.google.com/file/d/1FWgj2et_w67dj9ZGPZiiYnisRNc0sqAr/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"facility", icon:"gauge", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"Facility Monitoring System", tagline:"เฝ้าระวังระบบสาธารณูปโภค",
    description:"ระบบเฝ้าระวังงานระบบและสาธารณูปโภคของอาคารแบบรวมศูนย์ แสดงสถานะและแจ้งเตือนเมื่อเกิดเหตุผิดปกติแบบเรียลไทม์",
    howto:["รวมสัญญาณจากอุปกรณ์งานระบบต่างๆ","ตั้งค่าหน้าจอสถานะและการแจ้งเตือน","กำหนดผู้รับแจ้งเหตุและขั้นตอนตอบสนอง"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"dcim", icon:"chart", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"DCIM", tagline:"Data Center Infrastructure Management",
    description:"ระบบบริหารโครงสร้างพื้นฐาน Data Center แบบรวมศูนย์ จัดการพื้นที่แร็ค พลังงาน การระบายความร้อน และทรัพย์สินในที่เดียว",
    howto:["จัดทำผังแร็คและทรัพย์สิน (Asset)","เชื่อมข้อมูลพลังงานและความเย็น","วิเคราะห์ความจุและวางแผนขยาย"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Training — DCIM Stulz (Slide)", url:"https://drive.google.com/file/d/1QL2DS8EJRYGWksfwLmKMFCoo75UhsA-t/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"bas", icon:"gauge", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"BAS", tagline:"Building Automation System",
    description:"ระบบควบคุมและบริหารงานอาคารอัตโนมัติ เชื่อมระบบไฟฟ้า ปรับอากาศ และความปลอดภัยให้ทำงานประสานกันอย่างมีประสิทธิภาพ",
    howto:["เชื่อมต่ออุปกรณ์งานระบบเข้าศูนย์ควบคุม","ตั้งค่าตารางและเงื่อนไขการทำงานอัตโนมัติ","มอนิเตอร์และปรับจูนเพื่อประหยัดพลังงาน"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"คู่มือการใช้ BAS และตัวอย่างกราฟิค", url:"https://drive.google.com/file/d/1cJrn0AYNIldEd_xmkuI67SB19FiTrRfC/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"asd", icon:"flame", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"HSSD / ASD", tagline:"Aspiration Smoke Detector",
    description:"ระบบตรวจจับควันแบบดูดอากาศความไวสูง (HSSD/ASD) ตรวจจับสัญญาณเพลิงไหม้ได้ตั้งแต่ระยะเริ่มต้น ก่อนลุกลาม",
    howto:["วางท่อดูดอากาศให้ครอบคลุมพื้นที่เสี่ยง","ตั้งค่าระดับความไวการตรวจจับ","ทดสอบและบำรุงรักษาตามรอบ"],
    videoId:"https://drive.google.com/file/d/1NxDexxj-lm_GwpomODE-vDL7wNy0GASW/view?usp=sharing",
    docs:[
      {title:"สไลด์ประกอบการเรียน HSSD/ASD", url:"https://drive.google.com/file/d/1I1U782LJDmCKoYfGTTN3pDB-bikj9ZX_/view?usp=sharing"},
      {title:"คู่มือการใช้งาน (Manual)", url:"https://drive.google.com/file/d/1eYVJymX_87zhsCxlDoSMPj5H3F2m9FGX/view?usp=drive_link"},
      {title:"วิดีโอสาธิตการกดใช้งาน (Playlist)", url:"https://www.youtube.com/playlist?list=PLNdBlpvN3Lga1Stoh7l-qGKor9c412W4b"},
    ],
    quizLink:"https://forms.gle/o2cMch69dv9gzUUt6",
  },
  { id:"firesuppression", icon:"flame", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Fire Suppression System", tagline:"ระบบดับเพลิงอัตโนมัติ",
    description:"ระบบดับเพลิงอัตโนมัติสำหรับ Data Center ด้วยก๊าซ/สารสะอาด ดับไฟได้รวดเร็วโดยไม่ทำลายอุปกรณ์อิเล็กทรอนิกส์",
    howto:["เลือกชนิดสารดับเพลิงให้เหมาะกับพื้นที่","ตรวจถังสาร หัวฉีด และระบบสั่งการ","ซ้อมแผนและทดสอบระบบตามมาตรฐาน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"watermist", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Water Mist", tagline:"HI-FOG — มาตรฐาน NFPA 750",
    description:"ระบบดับเพลิงด้วยหมอกน้ำแรงดันสูง (Water Mist / HI-FOG) ใช้น้ำปริมาณน้อยแต่ดับไฟได้อย่างมีประสิทธิภาพและปลอดภัยต่ออุปกรณ์ ตามมาตรฐาน NFPA 750",
    howto:["เข้าใจหลักการหมอกน้ำ (Water Mist)","ตรวจสอบและตั้งค่า Pre-action Valve","ทดสอบระบบและซ้อมแผนตอบสนอง"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Marioff EPU Customer Training", url:"https://drive.google.com/file/d/1IYMyFAKkvtmXv3doNHgaD1pI4S0JAlIY/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"ttk-water", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Water Leak Detection — TTK", tagline:"TTK FG-NET — ตรวจจับน้ำรั่ว",
    description:"ระบบตรวจจับน้ำรั่วด้วยสายเซนเซอร์ของ TTK ระบุตำแหน่งจุดรั่วได้แม่นยำ ป้องกันความเสียหายต่ออุปกรณ์ในห้องเซิร์ฟเวอร์/Data Center",
    howto:["วางสายเซนเซอร์ตามจุดเสี่ยงน้ำรั่ว","เชื่อมเข้าตัวควบคุม FG-NET และตั้งค่าโซน","ตั้งค่าการแจ้งเตือนและระบุตำแหน่ง","ทดสอบการตรวจจับเป็นระยะ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"ไฟล์ Water Leak (TTK)", url:"https://drive.google.com/file/d/1bOE67GRB2E2hpd_YqyciFCHrFYWKzSkc/view?usp=sharing"},
      {title:"การอัปเกรด Firmware ของ TTK", url:"https://drive.google.com/file/d/1JqCqS0Fen4gPo7Zpcd23P-Ht2xyeqTmG/view?usp=sharing"},
      {title:"Quick Start", url:"https://drive.google.com/file/d/1LDPMBlmCT-56CTdzQgQJiYwHjsSJK3nH/view?usp=sharing"},
      {title:"คู่มือการใช้งาน (Manual)", url:"https://drive.google.com/file/d/1SDWeZ7e5U5fkVImBerF1zBAr8d5BvzF0/view?usp=sharing"},
    ],
    demo:"fg-net-simulator.html", quizLink:"#",
  },
  { id:"elsa-water", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Water Leak Detection — ELSA", tagline:"ELSA 3L-DF/SP — ตรวจจับน้ำรั่ว",
    description:"ระบบตรวจจับรอยรั่วของเหลวของ ELSA (3L-DF/SP) พร้อมเครื่องจำลองการกดใช้งานให้พนักงานใหม่ฝึกก่อนลงงานจริง",
    howto:["เปิดเครื่องและสังเกต Self-test","เข้าเมนูและตั้งค่าด้วยปุ่ม 1-5","รับมือสถานการณ์รั่ว/สายขาด แล้วกด Silence","เคลียร์สถานะเมื่อแก้ไขเสร็จ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Manual Water Leak ELSA User Guide", url:"https://drive.google.com/file/d/1dSr8zHIFAKJP8bk2HIsmBqDhaOXO_W1I/view?usp=sharing"},
      {title:"การต่อสาย Water Leak ELSA", url:"https://drive.google.com/file/d/1o6OSxegNo14ck04kU_CAziNHzb1P5jk8/view?usp=sharing"},
      {title:"การปรับ Sensitivity ของ Water ELSA", url:"https://drive.google.com/file/d/1AJrI4JPmMA3GFGDyHoLITDFTj_bmj-Oy/view?usp=sharing"},
    ],
    demo:"water-leak.html", quizLink:"#",
  },
  { id:"ttk-oil", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Oil Leak Detection — TTK", tagline:"TTK FG-NET — ตรวจจับน้ำมันรั่ว",
    description:"ระบบตรวจจับน้ำมันรั่วของ TTK เช่น บริเวณถังน้ำมันเครื่องกำเนิดไฟฟ้า แจ้งเตือนทันทีเมื่อพบการรั่วซึม — ต่อได้ 2 แบบ: (1) ใช้ตัวควบคุม FG-NET ธรรมดา ร่วมกับกล่องเพิ่ม (add-on) หรือ (2) ใช้ FG-NET LL ที่ต่อเซนเซอร์ตรวจจับน้ำมันได้โดยตรง",
    howto:["เข้าใจการต่อ 2 แบบ: FG-NET + กล่องเพิ่ม หรือ FG-NET LL ต่อตรง","ติดตั้งเซนเซอร์ตรวจจับน้ำมันตามจุดเสี่ยง (รอบถัง/ท่อน้ำมัน)","ตั้งค่าการแจ้งเตือนเมื่อพบน้ำมันรั่ว","ทดสอบระบบตามรอบ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Quick Start — FG-NET LL", url:"https://drive.google.com/file/d/1DahBk5xVj7OfCN5AFt7fczUv7OgMFNbV/view?usp=sharing"},
    ],
    demo:"fg-net-simulator.html", quizLink:"#",
  },
  { id:"elsa-oil", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Oil Leak Detection — ELSA", tagline:"ELSA — ตรวจจับน้ำมันรั่ว",
    description:"ระบบตรวจจับน้ำมันรั่วของ ELSA สำหรับพื้นที่เสี่ยง เช่น ถังน้ำมันเครื่องกำเนิดไฟฟ้า",
    howto:["ติดตั้งเซนเซอร์ตรวจจับน้ำมันตามจุดเสี่ยง","ตั้งค่าการแจ้งเตือนเมื่อพบน้ำมันรั่ว","ทดสอบระบบตามรอบ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"คู่มือ Oil Leak ELSA", url:"https://drive.google.com/file/d/1nsoRHMq9EBEMadPr8Y0DeefsI-jGJImM/view?usp=sharing"},
      {title:"Elsa Oil Leak — Technical Document", url:"https://drive.google.com/file/d/14CB6H7uy1CTMtySzOgGemYl9saKyGuXT/view?usp=sharing"},
    ],
    quizLink:"#",
  },
  { id:"facerecognition", icon:"camera", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Face Recognition", tagline:"ระบบจดจำใบหน้า",
    description:"ระบบจดจำใบหน้าเพื่อควบคุมการเข้าออกพื้นที่หวงห้าม รวดเร็ว แม่นยำ และลดการสัมผัส เหมาะกับจุดคัดกรองความปลอดภัยสูง",
    howto:["ลงทะเบียนใบหน้าผู้มีสิทธิ์","ติดตั้งกล้องในตำแหน่งและแสงที่เหมาะสม","เชื่อมกับ Access Control และบันทึกประวัติ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"cctv", icon:"camera", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"CCTV", tagline:"ระบบกล้องวงจรปิด",
    description:"ระบบกล้องวงจรปิดเฝ้าระวังความปลอดภัยตลอด 24 ชั่วโมง พร้อมบันทึกภาพและวิเคราะห์เหตุการณ์ย้อนหลังได้",
    howto:["วางตำแหน่งกล้องให้ครอบคลุมจุดสำคัญ","ตั้งค่าการบันทึกและพื้นที่จัดเก็บ","ตรวจสอบภาพและการแจ้งเตือนเป็นระยะ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"accesscontrol", icon:"shield", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Access Control", tagline:"ระบบควบคุมการเข้าออก",
    description:"ระบบควบคุมการเข้าออกด้วยบัตร รหัส หรือไบโอเมตริก กำหนดสิทธิ์รายบุคคลและบันทึกประวัติการเข้าออกได้ครบถ้วน",
    howto:["กำหนดสิทธิ์และโซนการเข้าถึง","ติดตั้งเครื่องอ่านและล็อกประตู","ตรวจสอบประวัติและรายงานการเข้าออก"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"turnstile", icon:"door", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Turnstile", tagline:"ประตูกั้นทางเข้า-ออก",
    description:"ประตูกั้นแบบหมุน/ปีกผีเสื้อ ควบคุมให้คนเข้าออกได้ทีละคน ทำงานคู่กับ Access Control เพื่อป้องกันการลักลอบตามเข้า",
    howto:["เลือกชนิด Turnstile ให้เหมาะกับพื้นที่","เชื่อมกับระบบ Access Control","ทดสอบการเข้าออกและระบบความปลอดภัย"],
    videoId:"ScMzIvxBSi4", docs:[], demo:"boon-edam-service-tool.html", quizLink:"#",
  },
  { id:"mantrap", icon:"door", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Mantrap Door", tagline:"ประตูสองชั้น (Interlock)",
    description:"ประตูสองชั้นแบบ Interlock เปิดได้ครั้งละบาน ป้องกันการแอบตามเข้า (Tailgating) สำหรับพื้นที่ความปลอดภัยสูง",
    howto:["เข้าใจหลักการ Interlock สองประตู","เชื่อมกับ Access Control และเซนเซอร์","ทดสอบเงื่อนไขการเปิด-ปิดให้ปลอดภัย"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"revolving", icon:"door", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Revolving Door", tagline:"ประตูหมุน",
    description:"ประตูหมุนควบคุมการเข้าออก ป้องกัน Tailgating และช่วยรักษาสภาพแวดล้อมภายในอาคาร (อุณหภูมิ/ฝุ่น)",
    howto:["เลือกขนาดและชนิดประตูหมุน","ติดตั้งและเชื่อมระบบควบคุมการเข้าออก","ตรวจสอบความปลอดภัยและเซนเซอร์กันหนีบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"bollard", icon:"shield", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Bollard", tagline:"เสากั้นยานพาหนะ",
    description:"เสากั้นยานพาหนะแบบยก/ลดได้ ป้องกันรถพุ่งชนเข้าพื้นที่สำคัญ ควบคุมการเข้าออกของยานพาหนะที่จุดคัดกรอง",
    howto:["กำหนดจุดติดตั้งและระดับการป้องกัน","ติดตั้งและเชื่อมระบบควบคุม","ทดสอบการยก/ลดและสัญญาณเตือน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"roadblocker", icon:"shield", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Road Blocker", tagline:"Boon Edam — ระบบกั้นทาง / ควบคุมการเข้าออก",
    description:"Road Blocker คืออุปกรณ์กั้นขวางยานพาหนะสำหรับจุดคัดกรองความปลอดภัย ใช้คู่กับระบบควบคุมการเข้าออก (Access Control) ของ Boon Edam เพื่อป้องกันการบุกรุกเข้าพื้นที่ Data Center ครอบคลุมหลักการทำงาน การติดตั้ง และความปลอดภัยในการใช้งาน",
    howto:["เข้าใจหน้าที่ของ Road Blocker ในระบบรักษาความปลอดภัย","ศึกษาขั้นตอนการยก/ลดที่กั้นอย่างปลอดภัย","ตรวจสอบระบบควบคุมและสัญญาณเตือนก่อนใช้งาน","ปฏิบัติตามขั้นตอนความปลอดภัยเมื่อมีรถผ่าน"],
    videoId:"https://drive.google.com/file/d/1dg3bmifq5HzEGKOnWDgsdT69ybzqPZ-B/view?usp=drive_link",
    docs:[ {title:"เอกสารประกอบการเรียน Road Blocker", url:"https://drive.google.com/file/d/1-KAdRdCyrxL7RBONebfWgbYOxXu_fEDJ/view?usp=drive_link"} ],
    quizLink:"https://forms.gle/KzcGoX8dUNvXVEjM7",
  },
  { id:"strongroom", icon:"box", color:"var(--blue-800)", eyebrow:"SECURITY",
    name:"Strong Room", tagline:"ห้องนิรภัยทนไฟ/ทนบุกรุก",
    description:"ห้องนิรภัยทนไฟและทนการบุกรุก สำหรับปกป้องอุปกรณ์และข้อมูลสำคัญของ Data Center จากไฟไหม้ น้ำ และการเข้าถึงโดยไม่ได้รับอนุญาต",
    howto:["ออกแบบระดับการป้องกัน (ไฟ/บุกรุก)","ติดตั้งผนัง ประตู และระบบล็อกนิรภัย","เชื่อมกับระบบความปลอดภัยและตรวจสอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"datasafe", icon:"box", color:"var(--blue-800)", eyebrow:"SECURITY",
    name:"Datasafe", tagline:"ตู้นิรภัยเก็บสื่อข้อมูลทนไฟ",
    description:"ตู้นิรภัยเก็บสื่อข้อมูลทนไฟ ป้องกันความร้อนและความชื้น รักษาเทปแบ็กอัพและสื่อบันทึกสำคัญให้ปลอดภัยจากเพลิงไหม้",
    howto:["เลือกระดับการทนไฟให้เหมาะกับสื่อ","จัดเก็บสื่อข้อมูลในตู้อย่างเป็นระบบ","ตรวจสอบสภาพและซีลตู้เป็นระยะ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
];
