/* ============================================================
   SITEM Academy — ข้อมูลบทเรียนทั้งหมด (แก้เนื้อหา "ที่ไฟล์นี้")
   แต่ละบท: id, icon, color, eyebrow(หมวด), name, tagline, description,
            howto[], videoId, docs[], demo(ถ้ามี), quizLink
   * ไฟล์นี้ต้องอยู่โฟลเดอร์เดียวกับ index.html เสมอ *
   ============================================================ */
const PRODUCTS = [
  { id:"company", icon:"building", color:"var(--blue-500)", eyebrow:"ONBOARDING",
    name:"รู้จัก SITEM", tagline:"ประวัติบริษัท วิสัยทัศน์ และมาตรฐาน ISO 9001:2015",
    description:"Site Preparation Management (SITEM) คือผู้เชี่ยวชาญด้านการออกแบบ ก่อสร้าง และดูแลรักษา Data Center รวมถึงจัดจำหน่ายอุปกรณ์ระดับโลก ด้วยมาตรฐาน ISO 9001:2015 — Data Center ต้องถูกสร้างโดยมืออาชีพ",
    howto:["ทำความเข้าใจวิสัยทัศน์และบริการหลักของ SITEM","รู้จักกลุ่มผลิตภัณฑ์ของบริษัท","ศึกษามาตรฐานคุณภาพและความปลอดภัยในงาน Data Center"],
    videoId:"https://drive.google.com/file/d/1pNpjYSqnGPmRcITj0NvyoOPtvJdljuXT/view?usp=sharing",
    docs:[
      {title:"ไฟล์วิดีโอ รู้จัก SITEM", url:"https://drive.google.com/file/d/1pNpjYSqnGPmRcITj0NvyoOPtvJdljuXT/view?usp=sharing"},
    ],
    quizLink:null,
  },
  { id:"generator", icon:"zap", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Generator", tagline:"เครื่องกำเนิดไฟฟ้าสำรอง",
    description:"เครื่องกำเนิดไฟฟ้าสำรองสำหรับ Data Center จ่ายไฟเมื่อไฟหลักดับเป็นเวลานาน เพื่อให้ระบบทำงานต่อเนื่องไม่สะดุด",
    howto:["ตรวจระดับน้ำมันเชื้อเพลิงและแบตเตอรี่สตาร์ท","ทดสอบเดินเครื่อง (Test Run) ตามรอบ","ตรวจระบบระบายความร้อนและไอเสีย"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"activefilter", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Active Filter & TPO", tagline:"ปรับปรุงคุณภาพไฟฟ้า / ลดฮาร์มอนิก",
    description:"Active Harmonic Filter และ TPO ช่วยลดฮาร์มอนิกในระบบไฟฟ้าและปรับปรุงค่าตัวประกอบกำลัง ทำให้อุปกรณ์ทำงานเสถียรและประหยัดพลังงาน",
    howto:["ตรวจวัดค่าฮาร์มอนิกในระบบก่อนติดตั้ง","ตั้งค่าฟิลเตอร์ให้เหมาะกับโหลด","มอนิเตอร์ค่าหลังติดตั้งให้อยู่ในเกณฑ์"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"ats", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"ATS", tagline:"Automatic Transfer Switch",
    description:"สวิตช์สับเปลี่ยนแหล่งจ่ายไฟอัตโนมัติ จากไฟหลักไปยังเครื่องกำเนิดไฟฟ้าเมื่อไฟดับ และสลับกลับเมื่อไฟหลักมาปกติ",
    howto:["เข้าใจลำดับการสลับแหล่งไฟ (Utility/Generator)","ตั้งค่าเวลาหน่วงและเงื่อนไขการสลับ","ทดสอบการสลับอัตโนมัติตามรอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"sts", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"STS", tagline:"Static Transfer Switch",
    description:"สวิตช์สับเปลี่ยนแหล่งจ่ายไฟแบบสถานะคงที่ ความเร็วสูง สลับแหล่งไฟได้ในเสี้ยววินาทีโดยโหลดไม่สะดุด",
    howto:["เข้าใจหลักการสลับแบบไร้รอยต่อ (Seamless)","ตรวจสอบแหล่งไฟทั้งสองฝั่งให้พร้อม","ทดสอบการสลับและตรวจสัญญาณเตือน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"loadbank", icon:"gauge", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Loadbank", tagline:"อุปกรณ์ทดสอบโหลด",
    description:"อุปกรณ์จำลองโหลดไฟฟ้า เพื่อทดสอบเครื่องกำเนิดไฟฟ้าและ UPS ว่ารับโหลดเต็มพิกัดได้จริงและเสถียร",
    howto:["กำหนดระดับโหลดที่ต้องการทดสอบ","ค่อยๆ เพิ่มโหลดเป็นขั้นและบันทึกค่า","ตรวจอุณหภูมิและแรงดันระหว่างทดสอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"pdu", icon:"plug", color:"var(--amber-500)", eyebrow:"POWER",
    name:"PDU / รางไฟฟ้า", tagline:"Power Distribution Unit / Busway",
    description:"ระบบจ่ายและกระจายไฟฟ้าไปยังตู้แร็ค พร้อมรางไฟฟ้า (Busway) ที่ยืดหยุ่น ติดตั้งง่าย และวัดค่าการใช้พลังงานรายจุดได้",
    howto:["วางผังการจ่ายไฟให้สมดุลแต่ละเฟส","ติดตั้ง PDU/Busway และต่อโหลดตามพิกัด","มอนิเตอร์การใช้พลังงานรายแร็ค"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"ups", icon:"battery", color:"var(--amber-500)", eyebrow:"POWER",
    name:"UPS", tagline:"Uninterruptible Power Supply",
    description:"ระบบ UPS จ่ายไฟสำรองทันทีเมื่อไฟหลักดับ ป้องกันอุปกรณ์ดับกะทันหันระหว่างรอเครื่องกำเนิดไฟฟ้าทำงาน",
    howto:["ตรวจสอบขนาด UPS ให้เหมาะกับโหลด","ติดตั้งและต่อสายกราวด์ให้ถูกต้อง","ทำ Preventive Maintenance และตรวจแบตเตอรี่"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"dynamicups", icon:"battery", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Dynamic UPS", tagline:"Diesel Rotary UPS (DRUPS)",
    description:"UPS แบบหมุน (DRUPS) ที่รวมเครื่องกำเนิดไฟฟ้าและ UPS ไว้ในตัวเดียว ให้ไฟต่อเนื่องระยะยาวโดยไม่ต้องใช้แบตเตอรี่จำนวนมาก",
    howto:["เข้าใจหลักการพลังงานสะสมแบบล้อหมุน (Flywheel)","ตรวจระบบเครื่องยนต์ดีเซลและคลัตช์","ทดสอบการจ่ายไฟต่อเนื่องตามรอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"battery", icon:"battery", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Battery", tagline:"แบตเตอรี่สำรอง",
    description:"แบตเตอรี่สำรองสำหรับระบบ UPS ทั้งแบบตะกั่วกรด (VRLA) และลิเธียม เลือกให้เหมาะกับเวลาสำรองไฟและพื้นที่",
    howto:["เลือกชนิดและความจุแบตให้ตรงความต้องการ","ติดตั้งในที่ระบายอากาศและอุณหภูมิเหมาะสม","ตรวจสภาพและเปลี่ยนตามอายุการใช้งาน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"batterymonitoring", icon:"gauge", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Battery Monitoring", tagline:"ระบบเฝ้าระวังแบตเตอรี่",
    description:"ระบบเฝ้าระวังสุขภาพแบตเตอรี่รายเซลล์ (แรงดัน อุณหภูมิ ความต้านทานภายใน) แจ้งเตือนล่วงหน้าก่อนแบตเสื่อมจนใช้งานไม่ได้",
    howto:["ติดตั้งเซนเซอร์วัดรายเซลล์","ตั้งค่าเกณฑ์แจ้งเตือน","ดูแนวโน้มสุขภาพแบตเพื่อวางแผนเปลี่ยน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"genstart", icon:"zap", color:"var(--amber-500)", eyebrow:"POWER",
    name:"Gen Start", tagline:"ระบบสั่งสตาร์ทเครื่องกำเนิดไฟฟ้า",
    description:"ระบบสั่งสตาร์ทเครื่องกำเนิดไฟฟ้าอัตโนมัติเมื่อตรวจพบไฟหลักดับ ให้แหล่งไฟสำรองพร้อมจ่ายในเวลาอันรวดเร็ว",
    howto:["เข้าใจสัญญาณสั่งสตาร์ทจากระบบไฟหลัก","ตั้งค่าเวลาหน่วงและเงื่อนไขสตาร์ท","ทดสอบการสตาร์ทอัตโนมัติตามรอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  /* demo: c7000-sim.html = เครื่องจำลอง STULZ C7000 */
  { id:"pac", icon:"snow", color:"var(--blue-400)", eyebrow:"COOLING",
    name:"Precision Air Conditioning", tagline:"ปรับอากาศความแม่นยำสูง (STULZ)",
    description:"ระบบปรับอากาศความแม่นยำสูงสำหรับ Data Center ควบคุมอุณหภูมิและความชื้นให้คงที่ตลอด 24 ชั่วโมง เพื่อให้อุปกรณ์ทำงานในสภาวะที่เหมาะสม",
    howto:["เข้าใจหลักการ Precision Cooling","ติดตั้ง CRAC/CRAH และจัดทิศทางลมเย็น/ลมร้อน","ควบคุมอุณหภูมิ ความชื้น และตรวจฟิลเตอร์"],
    videoId:"ScMzIvxBSi4", docs:[], demo:"c7000-sim.html", quizLink:"#",
  },
  { id:"vrf", icon:"fan", color:"var(--blue-400)", eyebrow:"COOLING",
    name:"VRF / VRV", tagline:"ระบบปรับอากาศปริมาณน้ำยาแปรผัน",
    description:"ระบบปรับอากาศแบบปรับปริมาณน้ำยาแปรผัน (VRF/VRV) ประหยัดพลังงาน ยืดหยุ่นต่อการแบ่งโซน เหมาะกับพื้นที่สำนักงานและห้องสนับสนุน",
    howto:["ออกแบบการแบ่งโซนและคอยล์ภายใน","ติดตั้งชุดคอนเดนเซอร์และเดินท่อน้ำยา","ตั้งค่าควบคุมและตรวจประสิทธิภาพ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"monitoring", icon:"chart", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"Power & Environmental Monitoring", tagline:"Packet Power / EMX",
    description:"ระบบมอนิเตอร์พลังงานและสภาพแวดล้อมแบบเรียลไทม์ด้วย Packet Power และ EMX เฝ้าระวังการใช้พลังงาน อุณหภูมิ และความชื้นภายใน Data Center",
    howto:["ติดตั้ง Smart Power Cables วัดพลังงานรายจุด","เชื่อม Gateway เข้าระบบเครือข่าย","ตั้งค่า Alerts & Policies แจ้งเตือนค่าผิดปกติ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"facility", icon:"gauge", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"Facility Monitoring System", tagline:"เฝ้าระวังระบบสาธารณูปโภค",
    description:"ระบบเฝ้าระวังงานระบบและสาธารณูปโภคของอาคารแบบรวมศูนย์ แสดงสถานะและแจ้งเตือนเมื่อเกิดเหตุผิดปกติแบบเรียลไทม์",
    howto:["รวมสัญญาณจากอุปกรณ์งานระบบต่างๆ","ตั้งค่าหน้าจอสถานะและการแจ้งเตือน","กำหนดผู้รับแจ้งเหตุและขั้นตอนตอบสนอง"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"dcim", icon:"chart", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"DCIM", tagline:"Data Center Infrastructure Management",
    description:"ระบบบริหารโครงสร้างพื้นฐาน Data Center แบบรวมศูนย์ จัดการพื้นที่แร็ค พลังงาน การระบายความร้อน และทรัพย์สินในที่เดียว",
    howto:["จัดทำผังแร็คและทรัพย์สิน (Asset)","เชื่อมข้อมูลพลังงานและความเย็น","วิเคราะห์ความจุและวางแผนขยาย"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"bas", icon:"gauge", color:"var(--cyan-500)", eyebrow:"MONITORING",
    name:"BAS", tagline:"Building Automation System",
    description:"ระบบควบคุมและบริหารงานอาคารอัตโนมัติ เชื่อมระบบไฟฟ้า ปรับอากาศ และความปลอดภัยให้ทำงานประสานกันอย่างมีประสิทธิภาพ",
    howto:["เชื่อมต่ออุปกรณ์งานระบบเข้าศูนย์ควบคุม","ตั้งค่าตารางและเงื่อนไขการทำงานอัตโนมัติ","มอนิเตอร์และปรับจูนเพื่อประหยัดพลังงาน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"asd", icon:"flame", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"HSSD / ASD", tagline:"Aspiration Smoke Detector",
    description:"ระบบตรวจจับควันแบบดูดอากาศความไวสูง (HSSD/ASD) ตรวจจับสัญญาณเพลิงไหม้ได้ตั้งแต่ระยะเริ่มต้น ก่อนลุกลาม",
    howto:["วางท่อดูดอากาศให้ครอบคลุมพื้นที่เสี่ยง","ตั้งค่าระดับความไวการตรวจจับ","ทดสอบและบำรุงรักษาตามรอบ"],
    videoId:"https://drive.google.com/file/d/1NxDexxj-lm_GwpomODE-vDL7wNy0GASW/view?usp=sharing",
    docs:[
      {title:"สไลด์ประกอบการเรียน HSSD/ASD", url:"https://drive.google.com/file/d/1I1U782LJDmCKoYfGTTN3pDB-bikj9ZX_/view?usp=sharing"},
      {title:"คู่มือการใช้งาน (Manual)", url:"https://drive.google.com/file/d/1eYVJymX_87zhsCxlDoSMPj5H3F2m9FGX/view?usp=drive_link"},
      {title:"วิดีโอสาธิตการกดใช้งาน (Playlist)", url:"https://www.youtube.com/playlist?list=PLNdBlpvN3Lga1Stoh7l-qGKor9c412W4b"},
    ],
    quizLink:"https://forms.gle/o2cMch69dv9gzUUt6",
  },
  { id:"firesuppression", icon:"flame", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Fire Suppression System", tagline:"ระบบดับเพลิงอัตโนมัติ",
    description:"ระบบดับเพลิงอัตโนมัติสำหรับ Data Center ด้วยก๊าซ/สารสะอาด ดับไฟได้รวดเร็วโดยไม่ทำลายอุปกรณ์อิเล็กทรอนิกส์",
    howto:["เลือกชนิดสารดับเพลิงให้เหมาะกับพื้นที่","ตรวจถังสาร หัวฉีด และระบบสั่งการ","ซ้อมแผนและทดสอบระบบตามมาตรฐาน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"watermist", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Water Mist", tagline:"HI-FOG — มาตรฐาน NFPA 750",
    description:"ระบบดับเพลิงด้วยหมอกน้ำแรงดันสูง (Water Mist / HI-FOG) ใช้น้ำปริมาณน้อยแต่ดับไฟได้อย่างมีประสิทธิภาพและปลอดภัยต่ออุปกรณ์ ตามมาตรฐาน NFPA 750",
    howto:["เข้าใจหลักการหมอกน้ำ (Water Mist)","ตรวจสอบและตั้งค่า Pre-action Valve","ทดสอบระบบและซ้อมแผนตอบสนอง"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"ttk-water", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Water Leak Detection — TTK", tagline:"TTK FG-NET — ตรวจจับน้ำรั่ว",
    description:"ระบบตรวจจับน้ำรั่วด้วยสายเซนเซอร์ของ TTK ระบุตำแหน่งจุดรั่วได้แม่นยำ ป้องกันความเสียหายต่ออุปกรณ์ในห้องเซิร์ฟเวอร์/Data Center",
    howto:["วางสายเซนเซอร์ตามจุดเสี่ยงน้ำรั่ว","เชื่อมเข้าตัวควบคุม FG-NET และตั้งค่าโซน","ตั้งค่าการแจ้งเตือนและระบุตำแหน่ง","ทดสอบการตรวจจับเป็นระยะ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"ไฟล์ Water Leak (TTK)", url:"https://drive.google.com/file/d/1bOE67GRB2E2hpd_YqyciFCHrFYWKzSkc/view?usp=sharing"},
      {title:"การอัปเกรด Firmware ของ TTK", url:"https://drive.google.com/file/d/1JqCqS0Fen4gPo7Zpcd23P-Ht2xyeqTmG/view?usp=sharing"},
      {title:"Quick Start", url:"https://drive.google.com/file/d/1LDPMBlmCT-56CTdzQgQJiYwHjsSJK3nH/view?usp=sharing"},
      {title:"คู่มือการใช้งาน (Manual)", url:"https://drive.google.com/file/d/1SDWeZ7e5U5fkVImBerF1zBAr8d5BvzF0/view?usp=sharing"},
    ],
    demo:"fg-net-simulator.html", quizLink:"#",
  },
  { id:"elsa-water", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Water Leak Detection — ELSA", tagline:"ELSA 3L-DF/SP — ตรวจจับน้ำรั่ว",
    description:"ระบบตรวจจับรอยรั่วของเหลวของ ELSA (3L-DF/SP) พร้อมเครื่องจำลองการกดใช้งานให้พนักงานใหม่ฝึกก่อนลงงานจริง",
    howto:["เปิดเครื่องและสังเกต Self-test","เข้าเมนูและตั้งค่าด้วยปุ่ม 1-5","รับมือสถานการณ์รั่ว/สายขาด แล้วกด Silence","เคลียร์สถานะเมื่อแก้ไขเสร็จ"],
    videoId:"ScMzIvxBSi4",
    docs:[],
    demo:"water-leak.html", quizLink:"#",
  },
  { id:"ttk-oil", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Oil Leak Detection — TTK", tagline:"TTK FG-NET — ตรวจจับน้ำมันรั่ว",
    description:"ระบบตรวจจับน้ำมันรั่วของ TTK เช่น บริเวณถังน้ำมันเครื่องกำเนิดไฟฟ้า แจ้งเตือนทันทีเมื่อพบการรั่วซึม — ต่อได้ 2 แบบ: (1) ใช้ตัวควบคุม FG-NET ธรรมดา ร่วมกับกล่องเพิ่ม (add-on) หรือ (2) ใช้ FG-NET LL ที่ต่อเซนเซอร์ตรวจจับน้ำมันได้โดยตรง",
    howto:["เข้าใจการต่อ 2 แบบ: FG-NET + กล่องเพิ่ม หรือ FG-NET LL ต่อตรง","ติดตั้งเซนเซอร์ตรวจจับน้ำมันตามจุดเสี่ยง (รอบถัง/ท่อน้ำมัน)","ตั้งค่าการแจ้งเตือนเมื่อพบน้ำมันรั่ว","ทดสอบระบบตามรอบ"],
    videoId:"ScMzIvxBSi4",
    docs:[
      {title:"Quick Start — FG-NET LL", url:"https://drive.google.com/file/d/1DahBk5xVj7OfCN5AFt7fczUv7OgMFNbV/view?usp=sharing"},
    ],
    demo:"fg-net-simulator.html", quizLink:"#",
  },
  { id:"elsa-oil", icon:"droplet", color:"var(--red-500)", eyebrow:"FIRE & DETECTION",
    name:"Oil Leak Detection — ELSA", tagline:"ELSA — ตรวจจับน้ำมันรั่ว",
    description:"ระบบตรวจจับน้ำมันรั่วของ ELSA สำหรับพื้นที่เสี่ยง เช่น ถังน้ำมันเครื่องกำเนิดไฟฟ้า (เนื้อหากำลังจัดทำ)",
    howto:["ติดตั้งเซนเซอร์ตรวจจับน้ำมันตามจุดเสี่ยง","ตั้งค่าการแจ้งเตือนเมื่อพบน้ำมันรั่ว","ทดสอบระบบตามรอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"facerecognition", icon:"camera", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Face Recognition", tagline:"ระบบจดจำใบหน้า",
    description:"ระบบจดจำใบหน้าเพื่อควบคุมการเข้าออกพื้นที่หวงห้าม รวดเร็ว แม่นยำ และลดการสัมผัส เหมาะกับจุดคัดกรองความปลอดภัยสูง",
    howto:["ลงทะเบียนใบหน้าผู้มีสิทธิ์","ติดตั้งกล้องในตำแหน่งและแสงที่เหมาะสม","เชื่อมกับ Access Control และบันทึกประวัติ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"cctv", icon:"camera", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"CCTV", tagline:"ระบบกล้องวงจรปิด",
    description:"ระบบกล้องวงจรปิดเฝ้าระวังความปลอดภัยตลอด 24 ชั่วโมง พร้อมบันทึกภาพและวิเคราะห์เหตุการณ์ย้อนหลังได้",
    howto:["วางตำแหน่งกล้องให้ครอบคลุมจุดสำคัญ","ตั้งค่าการบันทึกและพื้นที่จัดเก็บ","ตรวจสอบภาพและการแจ้งเตือนเป็นระยะ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"accesscontrol", icon:"shield", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Access Control", tagline:"ระบบควบคุมการเข้าออก",
    description:"ระบบควบคุมการเข้าออกด้วยบัตร รหัส หรือไบโอเมตริก กำหนดสิทธิ์รายบุคคลและบันทึกประวัติการเข้าออกได้ครบถ้วน",
    howto:["กำหนดสิทธิ์และโซนการเข้าถึง","ติดตั้งเครื่องอ่านและล็อกประตู","ตรวจสอบประวัติและรายงานการเข้าออก"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"turnstile", icon:"door", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Turnstile", tagline:"ประตูกั้นทางเข้า-ออก",
    description:"ประตูกั้นแบบหมุน/ปีกผีเสื้อ ควบคุมให้คนเข้าออกได้ทีละคน ทำงานคู่กับ Access Control เพื่อป้องกันการลักลอบตามเข้า",
    howto:["เลือกชนิด Turnstile ให้เหมาะกับพื้นที่","เชื่อมกับระบบ Access Control","ทดสอบการเข้าออกและระบบความปลอดภัย"],
    videoId:"ScMzIvxBSi4", docs:[], demo:"boon-edam-service-tool.html", quizLink:"#",
  },
  { id:"mantrap", icon:"door", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Mantrap Door", tagline:"ประตูสองชั้น (Interlock)",
    description:"ประตูสองชั้นแบบ Interlock เปิดได้ครั้งละบาน ป้องกันการแอบตามเข้า (Tailgating) สำหรับพื้นที่ความปลอดภัยสูง",
    howto:["เข้าใจหลักการ Interlock สองประตู","เชื่อมกับ Access Control และเซนเซอร์","ทดสอบเงื่อนไขการเปิด-ปิดให้ปลอดภัย"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"revolving", icon:"door", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Revolving Door", tagline:"ประตูหมุน",
    description:"ประตูหมุนควบคุมการเข้าออก ป้องกัน Tailgating และช่วยรักษาสภาพแวดล้อมภายในอาคาร (อุณหภูมิ/ฝุ่น)",
    howto:["เลือกขนาดและชนิดประตูหมุน","ติดตั้งและเชื่อมระบบควบคุมการเข้าออก","ตรวจสอบความปลอดภัยและเซนเซอร์กันหนีบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"bollard", icon:"shield", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Bollard", tagline:"เสากั้นยานพาหนะ",
    description:"เสากั้นยานพาหนะแบบยก/ลดได้ ป้องกันรถพุ่งชนเข้าพื้นที่สำคัญ ควบคุมการเข้าออกของยานพาหนะที่จุดคัดกรอง",
    howto:["กำหนดจุดติดตั้งและระดับการป้องกัน","ติดตั้งและเชื่อมระบบควบคุม","ทดสอบการยก/ลดและสัญญาณเตือน"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"roadblocker", icon:"shield", color:"var(--blue-700)", eyebrow:"SECURITY",
    name:"Road Blocker", tagline:"Boon Edam — ระบบกั้นทาง / ควบคุมการเข้าออก",
    description:"Road Blocker คืออุปกรณ์กั้นขวางยานพาหนะสำหรับจุดคัดกรองความปลอดภัย ใช้คู่กับระบบควบคุมการเข้าออก (Access Control) ของ Boon Edam เพื่อป้องกันการบุกรุกเข้าพื้นที่ Data Center ครอบคลุมหลักการทำงาน การติดตั้ง และความปลอดภัยในการใช้งาน",
    howto:["เข้าใจหน้าที่ของ Road Blocker ในระบบรักษาความปลอดภัย","ศึกษาขั้นตอนการยก/ลดที่กั้นอย่างปลอดภัย","ตรวจสอบระบบควบคุมและสัญญาณเตือนก่อนใช้งาน","ปฏิบัติตามขั้นตอนความปลอดภัยเมื่อมีรถผ่าน"],
    videoId:"https://drive.google.com/file/d/1dg3bmifq5HzEGKOnWDgsdT69ybzqPZ-B/view?usp=drive_link",
    docs:[ {title:"เอกสารประกอบการเรียน Road Blocker", url:"https://drive.google.com/file/d/1-KAdRdCyrxL7RBONebfWgbYOxXu_fEDJ/view?usp=drive_link"} ],
    quizLink:"https://forms.gle/KzcGoX8dUNvXVEjM7",
  },
  { id:"strongroom", icon:"box", color:"var(--blue-800)", eyebrow:"SECURITY",
    name:"Strong Room", tagline:"ห้องนิรภัยทนไฟ/ทนบุกรุก",
    description:"ห้องนิรภัยทนไฟและทนการบุกรุก สำหรับปกป้องอุปกรณ์และข้อมูลสำคัญของ Data Center จากไฟไหม้ น้ำ และการเข้าถึงโดยไม่ได้รับอนุญาต",
    howto:["ออกแบบระดับการป้องกัน (ไฟ/บุกรุก)","ติดตั้งผนัง ประตู และระบบล็อกนิรภัย","เชื่อมกับระบบความปลอดภัยและตรวจสอบ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
  { id:"datasafe", icon:"box", color:"var(--blue-800)", eyebrow:"SECURITY",
    name:"Datasafe", tagline:"ตู้นิรภัยเก็บสื่อข้อมูลทนไฟ",
    description:"ตู้นิรภัยเก็บสื่อข้อมูลทนไฟ ป้องกันความร้อนและความชื้น รักษาเทปแบ็กอัพและสื่อบันทึกสำคัญให้ปลอดภัยจากเพลิงไหม้",
    howto:["เลือกระดับการทนไฟให้เหมาะกับสื่อ","จัดเก็บสื่อข้อมูลในตู้อย่างเป็นระบบ","ตรวจสอบสภาพและซีลตู้เป็นระยะ"],
    videoId:"ScMzIvxBSi4", docs:[], quizLink:"#",
  },
];
